name: untitled
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  easy_localization: ^3.0.7


dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  # This is my package that generates text styles.
  textstyle_generator: ^0.1.1

flutter:

  uses-material-design: true

  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - lib/translations/

  fonts:
    - family: Inter-Black
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
    - family: Inter-BlackItalic
      fonts:
        - asset: assets/fonts/Inter-BlackItalic.ttf
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: Inter-BoldItalic
      fonts:
        - asset: assets/fonts/Inter-BoldItalic.ttf
    - family: Inter-ExtraBold
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf
    - family: Inter-ExtraBoldItalic
      fonts:
        - asset: assets/fonts/Inter-ExtraBoldItalic.ttf
    - family: Inter-ExtraLight
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf
    - family: Inter-ExtraLightItalic
      fonts:
        - asset: assets/fonts/Inter-ExtraLightItalic.ttf
    - family: Inter-Italic
      fonts:
        - asset: assets/fonts/Inter-Italic.ttf
    - family: Inter-Light
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
    - family: Inter-LightItalic
      fonts:
        - asset: assets/fonts/Inter-LightItalic.ttf
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: Inter-MediumItalic
      fonts:
        - asset: assets/fonts/Inter-MediumItalic.ttf
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Inter-SemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: Inter-SemiBoldItalic
      fonts:
        - asset: assets/fonts/Inter-SemiBoldItalic.ttf
    - family: Inter-Thin
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
    - family: Inter-ThinItalic
      fonts:
        - asset: assets/fonts/Inter-ThinItalic.ttf

    - family: Rufina-Bold
      fonts:
        - asset: assets/fonts/Rufina-Bold.ttf
    - family: Rufina-Regular
      fonts:
        - asset: assets/fonts/Rufina-Regular.ttf
    - family: SF-Pro-Display-Black
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.otf
    - family: SF-Pro-Display-BlackItalic
      fonts:
        - asset: assets/fonts/SF-Pro-Display-BlackItalic.otf
    - family: SF-Pro-Display-Bold
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
    - family: SF-Pro-Display-BoldItalic
      fonts:
        - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf
    - family: SF-Pro-Display-Heavy
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
    - family: SF-Pro-Display-HeavyItalic
      fonts:
        - asset: assets/fonts/SF-Pro-Display-HeavyItalic.otf
    - family: SF-Pro-Display-Light
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Light.otf
    - family: SF-Pro-Display-LightItalic
      fonts:
        - asset: assets/fonts/SF-Pro-Display-LightItalic.otf
    - family: SF-Pro-Display-Medium
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
    - family: SF-Pro-Display-MediumItalic
      fonts:
        - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf
    - family: SF-Pro-Display-Regular
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
    - family: SF-Pro-Display-RegularItalic
      fonts:
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
    - family: SF-Pro-Display-Semibold
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
    - family: SF-Pro-Display-SemiboldItalic
      fonts:
        - asset: assets/fonts/SF-Pro-Display-SemiboldItalic.otf
    - family: SF-Pro-Display-Thin
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
    - family: SF-Pro-Display-ThinItalic
      fonts:
        - asset: assets/fonts/SF-Pro-Display-ThinItalic.otf
    - family: SF-Pro-Display-Ultralight
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
    - family: SF-Pro-Display-UltralightItalic
      fonts:
        - asset: assets/fonts/SF-Pro-Display-UltralightItalic.otf
flutter_gen:
  output: lib/generated_assets/
  integrations:
    flutter_svg: false
    lottie: true
    rive: false
  assets:
    outputs:
      style: camel-case
      package_parameter_enabled: false